### ISSUE TITLE
Support for distinguishing data from parameters

### ISSUE THREAD

**Issue by tmcphillips** [yesworkflow-org/yw-prototypes#18]
The inputs to scripts, and to steps in scripts, often can be viewed either as *data* (the data to be processed by the script or step) or as *parameters* (values that control how that data is processed).  Currently it can be difficult to discern the (possibly more important) data flows in the views produced by YW-Graph from the (less important) application of parameter settings.  Here is a proposal for addressing this issue:

1.  Add support for `@param` comments on code blocks to indicate parameters. The existing `@in` comments would continue to be interpreted as data inflows.

2.  Add a setting to YW project files (see issue #16) for indicating that YW-Graph should emphasize graph nodes, edges, and labels representing data over those representing parameters, or to hide parameter flows entirely.

The future YW-Query module also should enable data and parameters to be distinguished.

**Comment by ludaesch** [comment]
Agreed. It's also a modeling question: do I, as the script/workflow author
view something as data or as a parameter. Yes, sometimes you don't want a
strict distinction or you do "meta-programming" where somebody's parameter
port is your data port.

Nevertheless (or because of that), a YW annotator should be able to express
his/her view on what is considered data and what is a parameter (in
addition to those two being treated differently by the runtime system; cf.
Kepler/Ptolemy)

On Thu, Feb 5, 2015 at 8:07 PM, Timothy McPhillips <notifications@github.com
