### ISSUE TITLE
R implementation examples?

### ISSUE THREAD

**Issue by olyerickson** [yesworkflow-org/yw-prototypes#27]
The (excellent!) YW presentations and papers discuss Py, Matlab and R implementations, but I can't find any specific example of YW annotation in R (which plays a key role in some of the papers). 

Where are the R examples? THANKS!!

**Comment by olyerickson** [comment]
Related to this, I'm trying to understanding the relationship (if any) of this to the NCEAS recordr work, esp. https://github.com/NCEAS/recordr

**Comment by tmcphillips** [comment]
Thanks for asking about this!  There are two R scripts marked up with YW annotations in the [incoming](https://github.com/yesworkflow-org/yw-prototypes/tree/master/incoming) directory: [AffyGeneExpressionAnalysisV12.R](https://github.com/yesworkflow-org/yw-prototypes/blob/master/incoming/AffyGeneExpressionAnalysisV12.R) and [LTVTP_CAR.R](https://github.com/yesworkflow-org/yw-prototypes/blob/master/incoming/LTVTP_CAR.R).  I hope these are helpful.

We'd like to look into integrating [recordr](https://github.com/NCEAS/recordr) with YW in the near future. We currently are exploring how best to integrate YW with the MATLAB analog of recordr, the [MATLAB DataONE Toolbox](https://github.com/DataONEorg/matlab-dataone). We are working on this in the [yw-matlab](https://github.com/yesworkflow-org/yw-matlab) repo. What we just got working was the ability to export the script run records made by the MATLAB RunManager and import them into YW so that the RunManager's authoritative list of input and output files for a script run can be used by the provenance reconstruction module of YW (instead of YW's default behavior of searching the file system for files that match the URI templates declared for `@in` and `@out` ports in the script).  Hopefully, we'll be able to do the same thing for R via recordr.  

The general idea is to integrate as much retrospective provenance information from as many sources as possible in YW and make this information available to query in terms of the prospective provenance declared via YW annotations.

**Comment by olyerickson** [comment]
Thanks very much for these pointers; most helpful!

Also thanks for the update on your next steps w.r.t. R and Matlab
integration.

On Thu, Dec 3, 2015 at 9:13 PM, Timothy McPhillips <notifications@github.com
> wrote:

> Thanks for asking about this! There are two R scripts marked up with YW
> annotations in the incoming
> <https://github.com/yesworkflow-org/yw-prototypes/tree/master/incoming>
> directory: AffyGeneExpressionAnalysisV12.R
> <https://github.com/yesworkflow-org/yw-prototypes/blob/master/incoming/AffyGeneExpressionAnalysisV12.R>
> and LTVTP_CAR.R
> <https://github.com/yesworkflow-org/yw-prototypes/blob/master/incoming/LTVTP_CAR.R>.
> I hope these are helpful.
>
> We'd like to look into integrating recordr
> <https://github.com/NCEAS/recordr> with YW in the near future. We
> currently are exploring how best to integrate YW with the MATLAB analog of
> recordr, the MATLAB DataONE Toolbox
> <https://github.com/DataONEorg/matlab-dataone>. We are working on this in
> the yw-matlab <https://github.com/yesworkflow-org/yw-matlab> repo. What
> we just got working was the ability to export the script run records made
> by the MATLAB RunManager and import them into YW so that the RunManager's
> authoritative list of input and output files for a script run can be used
> by the provenance reconstruction module of YW (instead of YW's default
> behavior of searching the file system for files that match the URI
> templates declared for @in and @out ports in the script). Hopefully,
> we'll be able to do the same thing for R via recordr.
>
> The general idea is to integrate as much retrospective provenance
> information from as many sources as possible in YW and make this
> information available to query in terms of the prospective provenance
> declared via YW annotations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yesworkflow-org/yw-prototypes/issues/27#issuecomment-161851306>
> .
>



-- 
John S. Erickson, Ph.D.
Director of Operations, The Rensselaer IDEA
Deputy Director, Web Science Research Center (RPI)
<http://tw.rpi.edu> <olyerickson@gmail.com>
Twitter & Skype: olyerickson

**Comment by olyerickson** [comment]
Closing this issue, since it answers our immediate question. Thanks!
