### ISSUE TITLE
Issues processing "simulate_data_collection.py" with YW

### ISSUE THREAD

**Issue by olyerickson** [yesworkflow-org/yw-prototypes#32]
I attempted to process "simulate_data_collection.py" using the steps in the prototypes README and had issues that I'd like to understand...

1. First, YW didn't understand the block comment syntax """, so it found no YW markup. 
2. I edited the file, changing to the # comment syntax; now, running...
```
yw extract simulate_data_collection.py -c extract.listfile
```
...it found the commands. 

3. Now running...
```
yw graph simulate_data_collection.py
```
...it doesn't generate anything. 

I'm definitely missing something!

**Comment by olyerickson** [comment]
I'm going to clone the repo and try again...

**Comment by olyerickson** [comment]
By cloning the repo, plopping the jars in a good spot and re-running, I was able to generate what appear to be the expected results.

I barely know why, however! In particular, I'm trying to understand how various config files and stuff in subdirectories make a difference... ;)

**Comment by tmcphillips** [comment]
Here are two things that should work *without* cloning the repo:

(1) Download just the [simulate_data_collection.py](https://raw.githubusercontent.com/yesworkflow-org/yw-prototypes/master/src/main/resources/examples/simulate_data_collection/simulate_data_collection.py) script to your local system.  Make sure there is no `yw.properties` or `yw.yaml` file in the directory where you save the script. Create the default graphical view of the script:
```
yw graph simulate_data_collection.py | dot -Tpdf -o default.pdf
```
Then open default.pdf in a PDF viewer.  You should see a horizontally-oriented process view of the script.

(2) Into the same directory as the script above download this [yw.properties](https://raw.githubusercontent.com/yesworkflow-org/yw-prototypes/master/src/main/resources/examples/simulate_data_collection/yw/yw.properties) file.  Remove the `../` prefix from the `extract.sources` value, and the `xsb/` prefixes from the `recon.factsfile`,  `model.factsfile`, and `recon.factsfile` values.  Create the graph according to the properties in `yw.properties`:
```
yw graph
```
Because the value assigned to the `graph.dotfile` property is `combined.gv` you will see no output to the terminal despite the lack of redirection or pipes on the command line. The output will be stored in `combined.gv`.  To render this as a PDF:
```
 dot -Tpdf combined.gv -o combined.pdf
```

Does this help?
