### ISSUE TITLE
Develop a simple intermediate representation of YW data flow

### ISSUE THREAD

**Issue by swanskysong** [yesworkflow-org/yw-prototypes#6]

**Comment by csjx** [comment]
Just to clarify, as we've been maturing the ProvONE model, we had renamed the previous DataLink class to Channel, and then after more discussion, to prov:Location, but have since realized that Channel is most appropriate.  We are working on updating the model with a Channel class, however, in an effort to be as PROV-compatible as possible, are looking into subclassing prov:Communication, which looks to be the most appropriate class to model communications between Programs connected by Ports.
